### ISSUE TITLE
[Patch] Use Configuration File to Set "edge" Value

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/worldedge#3]
This patch sets the variable "edge" in init.lua from the minetest.conf file using the option "world_edge". If the option is not set, then it defaults to 30000. It also adds a line of output to the log showing what "edge" is set to.

[mod-worldedge__init.lua.diff.zip](https://github.com/minetest-mods/worldedge/files/392262/mod-worldedge__init.lua.diff.zip)

**Comment by DonBatman** [comment]
Thanks. I will review and add if it looks good later today.

**Comment by AntumDeluge** [comment]
Added pull request #5.
